version: '3.8'
name: HackthonWorkContainer
services:
  react:
    container_name: lang-container
    build: 
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - .:/workspace:cached
      - home:/home
    depends_on:
      - voicevox
    networks:
      - hackthon-network

  voicevox:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    container_name: voicevox-container
    ports:
      - 127.0.0.1:50021:50021
    volumes: 
      - voicevox-volumes:/voicevox-volumes
    networks:
      - hackthon-network

volumes:
  home:
  voicevox-volumes:

networks:
  hackthon-network: